# Base image
FROM ubuntu:16.04

# MAINTAINER
MAINTAINER dev

# node run env
RUN apt-get update  
RUN apt-get install autoconf cmake vim libbz2-dev libdb++-dev libdb-dev libssl-dev openssl libreadline-dev libtool libcurl4-openssl-dev libboost-all-dev -y


# port-can 
EXPOSE 8050
EXPOSE 8049
EXPOSE 8048
EXPOSE 8047
EXPOSE 8046
EXPOSE 8045
EXPOSE 3306
EXPOSE 27017
